version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          dependency_name: '~'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
    version_requirement_updates: 'widen_ranges'
